### ISSUE TITLE
Request Delete and upgrade objects/rooms

### ISSUE THREAD

**Issue by gasemans** [gjdwebserver/Hospital-Inc.#12]
Would be nice to be able to delete a room or upgrade/change a room or object

Now i have created the cheapest reception and i want to upgrade that.
(or is there a button or action i have missed?)

I have created a lab and that has i costs.
Would be nice to be able to delete that to reduce the costs

**Comment by gjdwebserver** [comment]
The delete option will be added to the room information UI soon(tm).

Will look into reception upgrades.

**Comment by stealthgun** [comment]
Fixed both option will be available in the next build
