### ISSUE TITLE
room information / building window out of screen

### ISSUE THREAD

**Issue by Helmond** [gjdwebserver/Hospital-Inc.#14]
sometimes the room building/ information screen gets somewhat out of the screen.
if this happens it is not possible to close it becouse the close button is out of screen

![image](https://user-images.githubusercontent.com/34791332/34319334-ce89e61a-e7df-11e7-9cc1-63ee6239cda2.png)

**Comment by gjdwebserver** [comment]
This is a known issue I am looking into a solution

**Comment by MrTheoW** [comment]
Could you make the windows movable? (just like in Operating systems) that way the player cold still place the window at an wished location and be able to make the close icon visible.
closing a window by focusing it and pressing escape is also a nice work around.

**Comment by Helmond** [comment]
there are many possibilities to solve this problem.
the movable one could also fail. I had the windows in a non visible or clickable location which makes it impossible to place anything on that location.
an option is to place them in the center of the screen just like the financials or research overview.

**Comment by gjdwebserver** [comment]
I have yet to find a solution on how to see if an screen is inside your viewport (the area of the game your monitor sees).

Atm a sort of work around is to play it in windowed mode and rezise the window so you can accualy see the window that you cant click, its not a nice work around but it works.

Still looking into this

**Comment by stronkie** [comment]
well the best thing you can do.. is make a fix part of your window the info box.. Whenever you click an item that has info (like what to built , what info patient , what info room) let the text be displayed there.. that way you do not have so many info windows open.. easy to program :)

**Comment by gjdwebserver** [comment]
The main focus of the next release (0.3.3) will be fixing this issue.

**Comment by gjdwebserver** [comment]
Issue is fixed in the next build (0.3.3)
