### ISSUE TITLE
loading game crash

### ISSUE THREAD

**Issue by Helmond** [gjdwebserver/Hospital-Inc.#15]
i get this crash pretty often just after beginning a new game ( 2 seconds)
![image](https://user-images.githubusercontent.com/34791332/34319829-af114826-e7eb-11e7-801b-bebf85241f7d.png)

Fatal error: [File:D:\Build\++UE4+Release-4.18+Compile\Sync\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp] [Line: 813] 
Rendering thread exception:
Fatal error: [File:D:\Build\++UE4+Release-4.18+Compile\Sync\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11Util.cpp] [Line: 233] 
Direct3DDevice->CreateBuffer(&Desc, NULL, UniformBufferResource.GetInitReference()) failed 
 at D:\Build\++UE4+Release-4.18+Compile\Sync\Engine\Source\Runtime\Windows\D3D11RHI\Private\D3D11UniformBuffer.cpp:159 
 with error DXGI_ERROR_DEVICE_REMOVED DXGI_ERROR_DRIVER_INTERNAL_ERROR

0x00000000974F3FB8 KERNELBASE.dll!UnknownFunction []
0x0000000076013540 Hospital.exe!UnknownFunction []
0x0000000075917FEB Hospital.exe!UnknownFunction []
0x0000000075952998 Hospital.exe!UnknownFunction []
0x00000000789DC668 Hospital.exe!UnknownFunction []
0x00000000789DF9F0 Hospital.exe!UnknownFunction []
0x00000000789DB0B2 Hospital.exe!UnknownFunction []
0x00000000789C45EF Hospital.exe!UnknownFunction []
0x0000000076D0FA92 Hospital.exe!UnknownFunction []
0x0000000076D06514 Hospital.exe!UnknownFunction []
0x0000000076D44D42 Hospital.exe!UnknownFunction []
0x0000000076D13972 Hospital.exe!UnknownFunction []
0x0000000076D132E7 Hospital.exe!UnknownFunction []
0x0000000076D123CE Hospital.exe!UnknownFunction []
0x0000000075ABBD2D Hospital.exe!UnknownFunction []
0x0000000075A621CC Hospital.exe!UnknownFunction []
0x0000000075A529D3 Hospital.exe!UnknownFunction []
0x0000000098D01FE4 KERNEL32.DLL!UnknownFunction []
0x000000009AEAEF91 ntdll.dll!UnknownFunction []
0x000000009AEAEF91 ntdll.dll!UnknownFunction []

**Comment by gjdwebserver** [comment]
I haven't seen this issue appear myself, can you provide more information about your system?

**Comment by Helmond** [comment]
that time i was testing on an quite old laptop
2nd generation i5 en intel graphics 3000 or something
to prevent the thing from levitating i had all the settings on low.
the file is on an local ssd and there is 8 GB ram
running on Windows 10

**Comment by gjdwebserver** [comment]
This is an issue within the engine itself, I can see multiple threads on the internet about it.
for example: 
https://answers.unrealengine.com/questions/707450/dxgi-error-device-removed-dxgi-error-driver-intern.html

seems this can help:
https://answers.unrealengine.com/questions/725825/engine-crashes-on-startup-418.html

**Comment by Helmond** [comment]
I will try it next year ;)
I wonder if it helps, the fix described is for AMD the laptop is intel only.
the startup screen and options do run fine don't they use the unreal engine?

**Comment by Helmond** [comment]
i see you made a new version. nice :)
i will download that one and see if the crash still occurs. 
i already checked if all my drivers were up to date and while checking this i found out I once installed an experimental non final version.
i will look into it
are there release notes?

**Comment by gjdwebserver** [comment]
Release notes are always posted as a dev blog:
https://gamejolt.com/games/hospitalinc/300549/devlog

**Comment by Helmond** [comment]
i haven't looked in this problem because it didn't occur anymore.
i read the devlog but couldn't find a short list with added features or fixed bugs

**Comment by gjdwebserver** [comment]
Im closing this issues, please let me know if it rehappens.
