### ISSUE TITLE
Let the people wait at the closest waiting bench

### ISSUE THREAD

**Issue by Helmond** [gjdwebserver/Hospital-Inc.#16]
I now have a game with 45 patients.
I have the level 3 reception. 
but still 12 people have to go to the reception.
after some sophisticated eye tracking of my patients is found out that sometimes the people go to the waiting bench as far away as possible :S 
this slows up the progress heavily. as long as the patient from the far bench is walking to the reception it can't handle other patients, which effectively make the wait time much much longer.

**Comment by gjdwebserver** [comment]
This is something that will be implemented later.

**Comment by MrTheoW** [comment]
In Theme Hospital the patients goes from the reception to the door of the room they need to be and knock. From there they find the nearest free seat available. maybe the same can be done with the reception.. First walk to the reception, and if there is a queue, find the nearest seat available.

**Comment by Helmond** [comment]
i also noticed that only 2 people make use of a bench with 3 seats

**Comment by stronkie** [comment]
it is also the reason why people get stuck.. they (the patients) seem to like the pre placed benches the most.. I think you should start benches free.. and then you can decide where to place the benches.. They indeed should wait near the room they want or need to go too..

**Comment by gjdwebserver** [comment]
Will be implemented in the 0.4 update.
