### ISSUE TITLE
No new illnesses 

### ISSUE THREAD

**Issue by Helmond** [gjdwebserver/Hospital-Inc.#19]
i just had a game where i cured around 200 patients.
they all had just 13 different diseases.
in the beginning unknown illnesses occur quite often. when there are about 10 known illnesses there wont come any new. after a research same story about 3 or 4 illnesses are added and that's it. it looks pretty unrealistic to me

**Comment by gjdwebserver** [comment]
This is correct gameplay, there are around 5-10 illnesses added per stage, i will monitor feedback on this and adjust it up (so you have more illnesses per game) when i think it benefits the game.

Stage 3 and 4 will have new illnesses aswell so when those stages are done you will have more illnesses in the game.

**Comment by gjdwebserver** [comment]
I will add a function to the game option menu that you can have the option to have all the illnesses active instead of just a couple of them. This to make it that can you choose what you want. Would this help for you?

**Comment by stronkie** [comment]
I think it will ruin the fun of the game.. If there is an selection of illnesses you can play with , you already know by forehand what rooms to built..  > edit > added suggestions to my original request thread

**Comment by Helmond** [comment]
i agree with @stronkie it might make the game easy to predict. 
as for now i think there might be a few more.
the vaccines still don't work i assume that's a feature that has to be implemented yet

**Comment by gjdwebserver** [comment]
Ive added the option, its default (by default) and if someone would like to have all the illnesses you set it to maximum.

Vaccines and stage 3 is something that still need to be developed and will be implemented at a later stage (prob version 0.4)

**Comment by gjdwebserver** [comment]
Next release will have a maximum settings to get all the possible Illnesses in the game.
Closing the issue for now
