### ISSUE TITLE
Bug : When people go into the long/short stay rooms

### ISSUE THREAD

**Issue by stronkie** [gjdwebserver/Hospital-Inc.#21]
They only use the first bed and they all stack on eachother (as you can see on my stream)

I did not check if they would leave.. but I think it is not working :)

Also when you place benches near the top LONG/SHORT rooms on the left side.. they are rotated wrong...

Also visible on my stream

**Comment by Helmond** [comment]
it also would be nice to have an overvieuw of how much percent of the room is used 
and how many time there is left till the first patient leaving the room

**Comment by gjdwebserver** [comment]
Both Bugs will be fixed in the next release
added "busy until" to patient information to show you when the patient will leave the room

**Comment by gjdwebserver** [comment]
Bug will be fixed in the next release
