### ISSUE TITLE
quality  settings don't work

### ISSUE THREAD

**Issue by Helmond** [gjdwebserver/Hospital-Inc.#25]
With latest update the settings for the quality don't work.
when setting the quality in the menu i normally already see the option working ( shadows dissapear)
with new update i see no difference and when i start the game the options didn't take effect.

**Comment by gjdwebserver** [comment]
Have you pressed apply?

**Comment by Helmond** [comment]
yes i pressed apply
if i go back to the quality settings the settings are on the selected setting.
but if i start the game the shaddows are still there.

**Comment by gjdwebserver** [comment]
wich settings did you use?
and is it just shadows that are not changing?

**Comment by Helmond** [comment]
i set everything on low
i don't recall if the other settings did work.
shadows is the one that is the easiest to see.
i will make a more detailed post later this week

**Comment by gjdwebserver** [comment]
I need to look into this, ive changes some small things how settings are applied i could be that shadows are now not updated.

**Comment by gjdwebserver** [comment]
Its fixed, was missing a variable where the options where set. 
Dunno how it got lost, but next build 0.3.3 this will be fixed
