### ISSUE TITLE
more names

### ISSUE THREAD

**Issue by Helmond** [gjdwebserver/Hospital-Inc.#31]
it might be a good idea to have more names for patients
i start to recognize a lot of names.
in the game i have now even a lot of people have the same name
![image](https://user-images.githubusercontent.com/34791332/35527448-0aaa88ee-052b-11e8-9584-3eb3b52791c5.png)
don't shoot at my terrible paint skills :)

**Comment by gjdwebserver** [comment]
I will be adding more names to the game atm there are 50 female and 50 male names.

**Comment by gjdwebserver** [comment]
Ive added 600 more names for update 0.4 will be adding more for 0.5.
