### ISSUE TITLE
short stay unit accommodates only 3 patients

### ISSUE THREAD

**Issue by Helmond** [gjdwebserver/Hospital-Inc.#32]
my short stay unit olny provides room for 3 patients?
there are 7 beds but only 3 are used.
the long stay unit has 6 beds and are all used.
![image](https://user-images.githubusercontent.com/34791332/35527752-0eb9a0fe-052c-11e8-906b-f1311457977a.png)

**Comment by gjdwebserver** [comment]
have you downloaded 0.3.3 yet? 
this issue should be resolved with the new version.

**Comment by Helmond** [comment]
quite sure it was version 0.3.3 i will check and let know an other time.

**Comment by gjdwebserver** [comment]
I just check my own changelog.
I fixed this after 0.3.3, but kinda forgot. Sorry about that

This is what i found under my own 0.4 changelog
- Fixed short stay units seating positions 

So this will be fixed with the next build of the game.
