### ISSUE TITLE
multiple patients sitting on same spot

### ISSUE THREAD

**Issue by gasemans** [gjdwebserver/Hospital-Inc.#9]
multiple patients sitting on same spot on the bench. This happend multeple times in a short time periode

**Comment by gjdwebserver** [comment]
Known Bug, working on a solution, patients atm look at there que position for seating (so when your the 2nd in the que you take seat 2). This will need to be sorted by getting a sitting postion filler so that the game looks wich seat is avalible.

**Comment by gjdwebserver** [comment]
Issue is solved in the next build
